apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: burr-sb-deploy
spec:
  params:
  - name: mavenMirrorUrl
    description: the maven mirror
    default: http://repo1.maven.apache.org/maven2
  resources: 
  - name: appSource
    type: git
  - name: appImage
    type: image
  tasks: 
   - name: build-java-app
     taskRef:
       name: build-app
     params:
      - name: contextDir
        value: springboot
      - name: mavenMirrorUrl
        value: "$(params.mavenMirrorUrl)"
      - name: dockerFile
        value: Dockerfile  
     resources:
      inputs:
        - name: source
          resource: appSource
      outputs:
        - name: builtImage
          resource: appImage
   - name: deploy-kn-service
     taskRef:
       name: kn
     runAfter:
      - build-java-app
     resources:
      inputs:
        - name: image
          resource: appImage
     params:
      - name: ARGS
        value:
        - "service"
        - "create"
        - "burr-sb-greeter"
        - "--force"
        - "--image=$(inputs.resources.image.url)"